<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="7" hostname="Shaheens-iMac.lan" failures="1" tests="1" name="Default test" time="6.11" errors="0" timestamp="15 May 2023 07:59:44 GMT">
  <testcase classname="TestAutomation" name="CreateComplex_post_Api" time="6.075">
    <failure type="java.lang.AssertionError" message="expected [Yasi] but found [Yasin]">
      <![CDATA[java.lang.AssertionError: expected [Yasi] but found [Yasin]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at TestAutomation.CreateComplex_post_Api(TestAutomation.java:145)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CreateComplex_post_Api -->
  <testcase classname="TestAutomation" name="ValidatePostApiUsingHashMap" time="0.0">
    <ignored/>
  </testcase> <!-- ValidatePostApiUsingHashMap -->
  <testcase classname="TestAutomation" name="PostComplexApi" time="0.0">
    <ignored/>
  </testcase> <!-- PostComplexApi -->
  <testcase classname="TestAutomation" name="verifyGetApiIsReturningValidResponse" time="0.0">
    <ignored/>
  </testcase> <!-- verifyGetApiIsReturningValidResponse -->
  <testcase classname="TestAutomation" name="ResponseValidation" time="0.0">
    <ignored/>
  </testcase> <!-- ResponseValidation -->
  <testcase classname="TestAutomation" name="ValidatePostApi" time="0.0">
    <ignored/>
  </testcase> <!-- ValidatePostApi -->
  <testcase classname="TestAutomation" name="PostApi" time="0.0">
    <ignored/>
  </testcase> <!-- PostApi -->
  <testcase classname="TestAutomation" name="BodyValidation" time="0.0">
    <ignored/>
  </testcase> <!-- BodyValidation -->
</testsuite> <!-- Default test -->
