<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="7" total="8" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-15T07:59:38Z" name="Default suite" finished-at="2023-05-15T07:59:44Z" duration-ms="6110">
    <groups>
    </groups>
    <test started-at="2023-05-15T07:59:38Z" name="Default test" finished-at="2023-05-15T07:59:44Z" duration-ms="6110">
      <class name="TestAutomation">
        <test-method signature="CreateComplex_post_Api()[pri:8, instance:TestAutomation@6bd61f98]" started-at="2023-05-15T07:59:38Z" name="CreateComplex_post_Api" finished-at="2023-05-15T07:59:44Z" duration-ms="6075" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Yasi] but found [Yasin]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Yasi] but found [Yasin]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at TestAutomation.CreateComplex_post_Api(TestAutomation.java:145)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateComplex_post_Api -->
      </class> <!-- TestAutomation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
